version: "3.8"

services:
  app:
    build: .
    ports:
      - "443:443"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
